# Generated by Django 5.2.1 on 2025-06-29 17:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('9c11d443-86b2-4380-8021-ec9772f018b7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
