# Generated by Django 5.2.4 on 2025-07-19 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('bac24c95-5638-4b25-b3ae-f762a508ec95'), editable=False, primary_key=True, serialize=False),
        ),
    ]
